### PR TITLE
fix: ✏️ Sync solutions from session management

### PR DESCRIPTION
**Pull request by HelpMe-Pls**
I updated the code to match with the video

### CODE REVIEW

**Comment by kentcdodds** [comment]
Thanks for this! I prefer the way it appears in the code so I made an update to make this flow better. I appreciate you calling this to my attention! Cheers!

**Comment by HelpMe-Pls** [comment]
@kentcdodds Thanks for the review, but the main point of my PR is that ALL the execises AFTER that lesson (`09.managed-sessions/03.solution.session-cookie`) aren't applying the changes from it, so that's why I was making changes in so many files.

**Comment by kentcdodds** [comment]
Oh, I understand. But I like the way the later exercises are currently. It's nice to be able to use the logout utility. Thanks!

**Comment by HelpMe-Pls** [comment]
Ahhh, now I get it. Cheers :smile:

**Pull request closed without merging**
